/*
 * Copyright (C) 2026 SysMLinJava, LLC.
 *
 * This file is part of the SysMLinJava framework.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package sysmlinjava.views.interactionssequencediagram;

import sysmlinjava.views.SysMLRendering;

/**
 * Command line (console) based sequential display of interaction messages
 * generated by a SysMLinJava model process. The display runs as a
 * {@code main()} operation and receives the interaction message information as
 * formatted strings that are displayed as log outputs on the console.
 * 
 * @author ModelerOne
 *
 */
public class InteractionMessageSequenceDisplay extends SysMLRendering
{
	/**
	 * Constant int value for the UDP port on which the interaction message strings
	 * will be received
	 */
	public static final int udpPort = 8892;
	/**
	 * Receiver of the interaction message strings
	 */
	InteractionMessageReceiver receiver;

	/**
	 * Constructor - constructs the receiver in preparation for run
	 */
	public InteractionMessageSequenceDisplay()
	{
		receiver = new InteractionMessageReceiver(udpPort);
	}

	/**
	 * Main for console process. Simply constructs the display and starts (runs) its
	 * receiver which receives the interaction message data and displays it as
	 * toString()s to the console.<br>
	 * <b>Note:</b> This simple text-based (console) display is part of the basic
	 * SysMLinJava tool set. More capable graphics-based displays are available
	 * commercially. See SysMLinJava.com for details.
	 * 
	 * @param args null arguments
	 */
	public static void main(String[] args)
	{
		InteractionMessageSequenceDisplay display = new InteractionMessageSequenceDisplay();
		display.receiver.run();
		Runtime.getRuntime().exit(0);
	}
}
